### ISSUE TITLE
How do I change it opening from mouseover to an icon click?

### ISSUE THREAD

**Issue by solrevdev** [Kiuryy/Bookmark_Sidebar#100]
I chose mouseover during setup and now I would like to try icon click but I cannot find this in settings. 

An amazing extension by the way. Very very polished!

**Comment by Kiuryy** [comment]
You can change this in the settings of the extension. To access the settings of the extension, you can right click the extension icon and click on "Options".

There, you find the according option under "Sidebar" > "Toggle" called "Open Sidebar", where you can specify how the sidebar can be opened.
