### ISSUE TITLE
Support Cross-Device Settings

### ISSUE THREAD

**Issue by hello-smile6** [Kiuryy/Bookmark_Sidebar#114]
Could you make an export function for Microsoft Edge using the Office single sign-on feature and data storage so that users of Microsoft Edge could have the extension settings synced automatically? The extension could then behave the same on all user devices. You could maybe also use GitHub and Google APIs too.

**Comment by hello-smile6** [comment]
If a user's browser extensions are synced, they probably want their settings synced.

**Comment by Kiuryy** [comment]
This is already handled by the browser. If you are logged in into your browser, the extensions and its settings will be synced. Of course this is only working, if you configured the sync settings of Edge (or Chrome) accordingly.

**Comment by hello-smile6** [comment]
@Kiuryy The user extension settings are not synced. Only the extensions are. That would mean that users could have the same settings on every device, similar to Microsoft's Office extension.

**Comment by Kiuryy** [comment]
No, the settings of the extensions are actually saved in the sync storage of the browser and therefore synced across your devices.
https://developer.chrome.com/docs/extensions/reference/storage/#property-sync

If this is not working for you, this is likely configured this way in the browser.

**Comment by hello-smile6** [comment]
So, your extension will have the same icon color and settings on two devices, no matter what, and is saved to Microsoft servers. Correct?

**Comment by Kiuryy** [comment]
Yes, if you enable extension syncing, the settings of the sidebar will also be synced.

**Comment by hello-smile6** [comment]
Yay! I hate it when some (most) extensions don't work right.

**Comment by hello-smile6** [comment]
So, all settings **are** synced, right?

**Comment by Kiuryy** [comment]
Yes. You cannot tell to only sync certain settings, since you have to implement either the local storage (nothing synced and cannot be activated) or sync storage API (everything is synced and you can deactivate) to save the settings, while the extension is using the later one.

**Comment by hello-smile6** [comment]
So it is all synced by default, just checking.

**Comment by hello-smile6** [comment]
From what I understand, sync is enabled from the start. So, I'm closing this issue.

- [ ] Confirm: Settings are synced automatically
