### ISSUE TITLE
Idea For Another Extension

### ISSUE THREAD

**Issue by hello-smile6** [Kiuryy/Bookmark_Sidebar#118]
# In-Browser File Manager Improvement
## Suggestion for Another Browser Extension
@Kiuryy Could you design an improved interface, based on the bookmark manager, for the Microsoft Edge file manager? accessible by typing `file:///C:/` in the URL bar)? I love to use it for looking at local files, but it is bland. I use it for navigating to a file.

**Comment by Kiuryy** [comment]
Thanks for sharing your idea. I cannot work on such an extension, since the sidebar extension is just a spare time project and already much work, so I cannot invest more time into another project.
