### ISSUE TITLE
Override "Create Bookmark" dialog

### ISSUE THREAD

**Issue by Kiuryy** [Kiuryy/Bookmark_Sidebar#12]
Override the default dialog when bookmarking a page via the icon right to the address bar.
- Search field for directories
- Tree list with all directories

**Comment by Kiuryy** [comment]
```
"chrome_ui_overrides" : {
  "bookmarks_ui": {
    "remove_button": "true",
    "remove_bookmark_shortcut": "true"
  }
}
```
https://developer.chrome.com/extensions/ui_override

This is currently only working in Dev channel of Chrome or with `--enable-override-bookmarks-ui=1`

**Comment by MartinLichtblau** [comment]
For this purpose I use [Faster Bookmars](https://chrome.google.com/webstore/detail/faster-bookmark-add-bookm/fibadljlplamppipiebabkdehecpabce?hl=en-US) since many years and it streamlines the process so much. Bookmarks Sidebar looks nice, but doesn't stand a chance regarding productivity.

**Comment by Annastaciahubbard** [comment]
The above link to the developers' page for the override, to test, is broken.

**Comment by Kiuryy** [comment]
Seems like Google removed this entirely from Chrome. Overriding the bookmark creation dialog is no longer possible, even on the dev channel.
