### ISSUE TITLE
[suggestion] a copy url button

### ISSUE THREAD

**Issue by RANKTW** [Kiuryy/Bookmark_Sidebar#120]
add a copy URL button would be really useful
![](https://sharex.host/qbE4dq9r8z.png/ks7Crmi4D7Xopj)

**Comment by hello-smile6** [comment]
> add a copy URL button would be really useful
> ![](https://camo.githubusercontent.com/808e5ed5af88e5d2eb50311d9675ec766c2657deb23f80cbb07704d0f0e0e491/68747470733a2f2f7368617265782e686f73742f7162453464713972387a2e706e672f6b733743726d69344437586f706a)

I agree.

**Comment by Kiuryy** [comment]
You can copy the URL by pressing ctrl+c when you hover a bookmark in the sidebar. Having a dedicated button is probably a good idea in terms of usability. I will try to add this button with the next release of the sidebar.

**Comment by Kiuryy** [comment]
Added a button in the contextmenu with 3eef9d424632ddb9b169c156305b291c007d4a4d.

The new release with this included in currently being approved by Google and should be available in a couple of days.
