### ISSUE TITLE
Glass theme doesn't work well

### ISSUE THREAD

**Issue by mrbeardad** [Kiuryy/Bookmark_Sidebar#127]
* **OS**: Manjaro Linux 2
* **browser**: Chrome89.0.4389.72-1

![image](https://user-images.githubusercontent.com/54128430/110069208-4c23d700-7db2-11eb-9a94-b2ad5d9654e6.png)

When move the mouse into the sidebar:
![image](https://user-images.githubusercontent.com/54128430/110069263-6493f180-7db2-11eb-80ae-9025fad76582.png)

**Comment by Kiuryy** [comment]
I think this is not related to the glass theme, but happening with the dark mode of Github, regardless of the theme. There seems to be a stylesheet conflict of the CSS from their dark mode and the extensions sidebar markup. 

The limitation of Chrome requires the extension to interact with the underlaying websites, which can cause conflicts with the script executions and stylesheets. It's impossible to make the sidebar compatible to every website, but I will try to figure out why this is happening on Github and what (or whether) I can do about this.

**Comment by Kiuryy** [comment]
I could find the reason for this issue and added a fix with b4e61a80385634580e837bdef81d06cb805f97b1. The next version of the extension, released soon will include this fix.

**Comment by mrbeardad** [comment]
Thanks a lot.
