### ISSUE TITLE
README.md links to not open in new tab

### ISSUE THREAD

**Issue by hello-smile6** [Kiuryy/Bookmark_Sidebar#128]
When you click a link on `README.md`, it opens in the current tab, even though it should open in a separate tab.

**Comment by Kiuryy** [comment]
Github seems to ignore `target=_blank` in Markdown, making this unfortunately not work here. I just tested the markup formatted like `[go](http://stackoverflow.com){:target="_blank"}` which does not work either.

https://stackoverflow.com/a/42156438/1660305
