### ISSUE TITLE
Port to Firefox

### ISSUE THREAD

**Issue by Kiuryy** [Kiuryy/Bookmark_Sidebar#17]
As Firefox is now capable of the WebExtension API, maybe with some changes the extension will work there, too.

**Comment by Kiuryy** [comment]
Added polyfill for the chrome object with d773b9376898c90d0410ea387506a0503977d410

I'm using now $.api everywhere instead of the chrome object (e.g. $.api.storage.sync, ...)

**Comment by guija** [comment]
Is this useful having in mind that Firefox has a built in bookmarks sidebar?

**Comment by Kiuryy** [comment]
It was just an idea I had when I heard about the WebExtension API support in Firefox, but it would need much more adaption to make it work there. Especially regarding Firefox users being used to have a permanent sidebar, so the interests of them compared to Chrome users differ.
Because of this it's not very likely I will work on a port, though :)

**Comment by Kiuryy** [comment]
A port doesn't seem to be that trivial and requires many adaptions despite having the WebExtension API
