### ISSUE TITLE
Provide screenshots for the translations

### ISSUE THREAD

**Issue by Kiuryy** [Kiuryy/Bookmark_Sidebar#23]
The translation texts need some information about where they are used. Providing screenshots for the abstract ones could help here.
Adding a button to report unclear translations could help, too.

**Comment by hello-smile6** [comment]
@Kiuryy Is this ever happening?

**Comment by Kiuryy** [comment]
This was an idea from the early days of the extension when there were just a few translations and far less language variables. I found another way of making translating the variables more clear by adding categories, help texts and a more structured translation overview Since the extension is now already translated into almost every language Chrome is available for, such a feature is not necessary anymore.
