### ISSUE TITLE
It loads continuously if there are no bookmarks

### ISSUE THREAD

**Issue by EdwardDiehl** [Kiuryy/Bookmark_Sidebar#3]
I completely removed all bookmarks and have these 2 folders empty:
`Bookmarks bar`
`Other bookmarks`

When i open bookmarks sidebar it shows loading indicator.
Expected behavior (IMO): it show folders.

One more note. In 20 minutes of this loading it seems that chrome consumed quite a lot of memory and become unresponsive and i had to restart it, i am not 100% sure that it is because of the continuous loading issue with the extension, i had only several other tabs opened.
![bm_continuously_loading](https://user-images.githubusercontent.com/657395/27251787-360773ac-5357-11e7-87ad-ad9066b5ae54.png)

**Comment by Kiuryy** [comment]
I can reproduce this behaviour with a newly installed browser. It works with no bookmars though, but when adding bookmarks and remove the last one, the extension will break. I will look for a fix for this.

**Comment by Kiuryy** [comment]
Should be fixed with 5974c69. The execution got stuck restoring the opened directories when a directory became empty but still stated as opened.

**Comment by EdwardDiehl** [comment]
:+1: looks like it is fixed
