### ISSUE TITLE
Bookmark removed from the search scope is still present in search.

### ISSUE THREAD

**Issue by EdwardDiehl** [Kiuryy/Bookmark_Sidebar#37]
Steps to reproduce:
1. Add a new bookmark.
2. Wait when sidebar will be reloaded.
3. Search for this bookmark in the search input in the sidebar.
4. Delete the bookmark in the search scope.
5. Reset search - click on the cross in the right side of the search input field.
6. Search for the same bookmark again. The bookmark is available in the search.

**Comment by Kiuryy** [comment]
I tested it myself and ran into the same issue, thanks for mentioning. With dd706ed1cf35cff035227e0dcf802de0f0cc448a the problem should be fixed.
