### ISSUE TITLE
Add possibility to turn off animations/visual effects

### ISSUE THREAD

**Issue by EdwardDiehl** [Kiuryy/Bookmark_Sidebar#4]
It would be really great if it would be possible to make all the animations, transitions and shadows optional. So one checkbox in setting for turning on-off all these thing would be a good improvement.
When you have a big amount of bookmarks and use the extension intensively then it is more important to make interface response time shorter.

**Comment by Kiuryy** [comment]
Adding such an option is not that trivial as all animations are css transitions (and there are many of them). I think adding a checkbox to disable them all is something I could add in the future, but this needs some time and an idea how to add this nicely to the existing template mechanism.

**Comment by Kiuryy** [comment]
With 6c8e571 I added an option to disable the entire animations to provide a faster interface. I'm still testing it and probably publish it  to the webstore tomorrow.
