### ISSUE TITLE
Overlay could have size control too..

### ISSUE THREAD

**Issue by EC-O-DE** [Kiuryy/Bookmark_Sidebar#42]
Overlay and tooltips.

**Comment by Kiuryy** [comment]
I think adding additional sliders for the overlay/tooltip width is too niche and won't provide much benefit. The layout of the content of the overlay for instance has to be changed according to the configured width, or the option wouldn't be useful at all. This would require many work and changes to the code.
Why do you want these to be configurable? Are they too small/large for your monitor, or is it just an idea for a "nice to have" feature?
