### ISSUE TITLE
Tag in a title of a bookmark

### ISSUE THREAD

**Issue by EdwardDiehl** [Kiuryy/Bookmark_Sidebar#43]
`Peity • progressive <canvas> pie charts`
this is the text in the title of the bookmark

![sidebar-issue](https://user-images.githubusercontent.com/657395/32554504-affa53d4-c4a2-11e7-92a2-cd78fcfbb38e.png)

**Comment by Kiuryy** [comment]
Fixed with 50d48cabae88c9007faf40043e19d57b495d362f
