### ISSUE TITLE
It does not save the entire page title if it contains single quotes

### ISSUE THREAD

**Issue by EdwardDiehl** [Kiuryy/Bookmark_Sidebar#46]
Title of this page is `When 'not' to use arrow functions`
In source code it is `When &#x27;not&#x27; to use arrow functions`
https://dmitripavlutin.com/when-not-to-use-arrow-functions-in-javascript/

When this page was added to bookmarks, the pages title was just `When`

**Comment by Kiuryy** [comment]
Thanks for mentioning, the problem is occuring whenever you try to add or edit a bookmark with the overlay dialog. I fixed it with ea3ed605274585db6e79d53e2c80daaa77e46207, so single quotes won't cut the rest of the title anymore.
