### ISSUE TITLE
CPU usage 100% and freeze on operations with big amounts of bookmarks

### ISSUE THREAD

**Issue by EdwardDiehl** [Kiuryy/Bookmark_Sidebar#5]
When i import big amount of bookmarks from firefox or move big amount of bookmarks (several thousands) from one directory to another one, then the extension consumes 100% cpu (see chrome process manager) and freezes the system, browser becomes unresponsive, for me it was quite a long time >10min.
Without the extension all these operations take several seconds and the browser works without freezing.

I didn't check yet the code of the extension carefully. I guess that it uses some kind of bookmarks indexing?

**Comment by Kiuryy** [comment]
I think this is related to the event Chrome triggers when you add or edit a bookmark. If this happens, the extensions reloads its content. Maybe Chrome triggers this event thousand of times when adding that many bookmarks at once. I will check this and try to find a solution.

**Comment by Kiuryy** [comment]
Should be fixed with 0115c81. The import task triggered a refresh event for every imported bookmark, now it only triggers once after all bookmarks have been imported.
