### ISSUE TITLE
Shortcut not working on slow loading pages

### ISSUE THREAD

**Issue by guija** [Kiuryy/Bookmark_Sidebar#54]
Hi, thanks for the great plugin, finally a nice sidebar for Chrome.

When I open sites that take long to load (or if i have a bad connection) the shortcut for the sidebar (In my case `Ctrl+Shift+B`) does not work (E.g. on http://www.faz.net). I also noticed that as long as the site has not been loaded completely the bookmarks overlay does not appear when I move my mouse near the border of the site (In my case left side).

**Comment by Kiuryy** [comment]
Thank you for your feedback. Unfortunately this is a limitation I cannot make anything about. Chrome loads the content scripts only as soon as the website is loaded (DOMContentReady), to not slow it down. This results in the sidebar only being able to open as soon as the content scripts has been injected and initialized successfully. 
There is no mechanism to load content inside the browser content without interacting with the underlaying page, which results in not only this issue.
