### ISSUE TITLE
Compatible with Opera/Vivaldi/Yandex

### ISSUE THREAD

**Issue by EC-O-DE** [Kiuryy/Bookmark_Sidebar#56]
This extension is compatible with Opera. And there shouldn't be no reason why not with Vivaldi and Yandex too.

Consider submitting Bookmark Sidebar to Opera Addons as well:
https://addons.opera.com/en/extensions/

**Comment by Kiuryy** [comment]
I already thought about making the extension also available for the other browsers (Opera/Vivaldi), but decided against doing.

The main problem is, that both of these browsers already have a native bookmark sidebar and therefore their users have another demands on what the extension should be doing. As it's just a togglable sidebar, which is fine for Chrome, I suppose, this will very likely not be true for Opera or Vivaldi users and I don't have planned to fragment the extension to add Opera/Vivaldi only features and maintaining two code bases. Maybe if I have more time to work on the extension, I will dive into this...

**Comment by EC-O-DE** [comment]
Ok. Great.
Well, this just works in  Opera the same as in Chrome - there's no issues (only Opera startpage cannot be overriden atm).

Anyhow, Opera users do get many of they're extensions from Chrome Store.

**Comment by MasterRedStorm** [comment]
@Kiuryy Do you think you will make this Plugin compatible with Firefox someday?
I found no "Good" BookmarkSidebar for FF and yours feels Amazing. :)
I consider switching to Chrome because of it.

**Comment by Kiuryy** [comment]
A port to Firefox isn't that trivial, since this browser is using a different implementation of the WebExtension API (#17). Currently I haven't planned to create such a port.
