### ISSUE TITLE
Settings sync to gist

### ISSUE THREAD

**Issue by hsuRush** [Kiuryy/Bookmark_Sidebar#59]
Create a new personal access token which has the gist scope in github and  sync it.
example: https://atom.io/packages/sync-settings

**Comment by Kiuryy** [comment]
The settings of the extension are already being synced, but using the build in Chrome mechanism for this. Can you give an example, what's the point of adding synchronisation with gist and why you are missing it?

**Comment by hsuRush** [comment]
Oh my bad! I didn't login to my google account in chrome, I am sorry. 
Well done!
