### ISSUE TITLE
Color settings are missing

### ISSUE THREAD

**Issue by hsuRush** [Kiuryy/Bookmark_Sidebar#60]
The color settings are missing after I switch the setting between Day mode and Night mode.

**Comment by Kiuryy** [comment]
You are right, when switching between dark and light mode, the color scheme is also getting changed to light/dark blue. I will change this behaviour to only change the color scheme if it's not the default blue color.

**Comment by Kiuryy** [comment]
The mask color and the color scheme are now only being changed when switching between dark and light theme, if they are the default value. User defined colors won't be changed anymore.
40cf7bf09e585de34d237fa211ffe95660467bb9

**Comment by hsuRush** [comment]
Well done!
