### ISSUE TITLE
黑色主题下的根本看不清楚图标

### ISSUE THREAD

**Issue by heartacker** [Kiuryy/Bookmark_Sidebar#62]
看图
![image](https://user-images.githubusercontent.com/1876302/45766152-7bd5d780-bc69-11e8-8ae3-532a28fb5d28.png)

**Comment by Kiuryy** [comment]
The default icon color is set to fit the default Chrome appearance and therefore is set to a dark gray, like the other system icons (navigation arrows, reload, ...).
But you can change the color of the icon in the settings of the extension. Under "Appearance" > "Icon" you find a color picker.
