### ISSUE TITLE
Are there keyboard shortcuts?

### ISSUE THREAD

**Issue by gennad** [Kiuryy/Bookmark_Sidebar#65]
Is there a shortcut to open the sidebar with the keyboard? And when opened, is there a shortcut to search for a bookmarK?

**Comment by Kiuryy** [comment]
There are some keyboard shortcuts implemented in the extension already. You can have a look at the available options by clicking the menu icon in the header of the sidebar and then click on the "Keyboard" icon in the lower right corner of the contextmenu. There you also find a reference to the page, where you can set up a shortcut to open/close the sidebar.

The search in behaving like the Windows startmenu search. If you have opened the sidebar, you can just start typing right away. There is no need for a dedicated shortcut.
