### ISSUE TITLE
Support deleting the empty directory

### ISSUE THREAD

**Issue by Vstory** [Kiuryy/Bookmark_Sidebar#67]
Check the bookmark function, please support deleting the empty directory.
If it can be supported.

**Comment by Kiuryy** [comment]
That's something worth considering for the "Bookmark Checker". There could be another tab at the left of the result page listing all empty directories. 
I will think about a good implementation for this and add it to the extension, if I find some time for it.

**Comment by Vstory** [comment]
Ok, look forward to the implementation of this feature.

**Comment by Kiuryy** [comment]
I extended the "Bookmark Checker" to also list all empty directories as a separate menupoint of the result page with 8ef67a9d97f122328ea2d8ac0e1c9a859497a54e. With the next release of the extension, this feature will be included.
