### ISSUE TITLE
icone color

### ISSUE THREAD

**Issue by Khalilsqu** [Kiuryy/Bookmark_Sidebar#74]
The icon is invisible! 

![image](https://user-images.githubusercontent.com/22060413/63109255-ab2bbc00-bf80-11e9-8f1b-1a96f2dc7f98.png)

![image](https://user-images.githubusercontent.com/22060413/63109633-8f74e580-bf81-11e9-9e5f-23cd3876fdd0.png)

Is it possible to change the colour of the icon?

**Comment by Kiuryy** [comment]
The icon color can be configured in the settings of the extension already. You can find the according option under `"Appearance" > "Icon"`. 

There you can either have the default automatic color selection, which is only working for a non-themed Chrome, or a custom color using the colorpicker.

**Comment by Khalilsqu** [comment]
Thanks, appreciate iy tour help.
