### ISSUE TITLE
How to set bookmarks page background？

### ISSUE THREAD

**Issue by PoplarYang** [Kiuryy/Bookmark_Sidebar#81]
I have paid, but I can't find where to change my background.

![image](https://user-images.githubusercontent.com/15922385/69481416-2c320380-0e4c-11ea-8e3c-142b865f5b4b.png)

**Comment by Kiuryy** [comment]
To change the background image of the new tab page, you need to click the "edit" icon in the lower corner of this page, to enter the edit mode.

If you do so, a button will appear in the lower corner of the page which you can click to upload an image. After you uploaded an image, you need to save your changes by clicking the according button in the bar at the bottom.
