### ISSUE TITLE
Add a button to open it

### ISSUE THREAD

**Issue by kilesduli** [Kiuryy/Bookmark_Sidebar#83]
As the title says.Like keyboard shortcut.

**Comment by Kiuryy** [comment]
You can already click on the extension icon (which is right to the address bar, or in the Chrome menu) to open/close the sidebar, as well as configuring a keyboard shortcut (chrome://extensions/shortcuts).

**Comment by kilesduli** [comment]
Yes, you are right.But it's not work in app mode(--app=http://).I don't know why chrome built-in shortcut keys is working.But configuring a keyboard shortcut cannot work.Maybe it is not necessary.
