### ISSUE TITLE
All bookmarks hidden?

### ISSUE THREAD

**Issue by megaroeny** [Kiuryy/Bookmark_Sidebar#84]
For some reason, today I noticed that all my bookmarks became hidden? How do I unhide them? I can only see how to show Hidden bookmarks. Thanks

**Comment by Kiuryy** [comment]
You can click the menu icon in the header of the sidebar. There you find a checkbox to show all hidden bookmarks and folders. Once you checked this, you can right click any of the hidden entries to unhide them. The according icon is located in the lower right of the contextmenu.

I heard about changes in Vivaldi causing bookmarks to be hidden after the update. It seems like after reinstalling the extension, everything is working fine. I'm not supporting Vivaldi actively, so cannot give accurate information.

Please let me know if the problem persists, so I can have a closer look at this.

**Comment by megaroeny** [comment]
I'm not seeing that button in the context menu:
![image](https://user-images.githubusercontent.com/1559447/72268148-4fc52f00-35ef-11ea-8f5b-f1f9f6bd4dcc.png)

Also, I am using the popular Chrome browser - Brave. They recently pushed out an update to fix issues they were having with Bookmarks syncing and they did some slight UI changes. Maybe this has something to do with it? — https://github.com/brave/brave-browser/issues/5158

**Comment by megaroeny** [comment]
I'm also on version 1.17.0 rev2 of the extension.

**Comment by Kiuryy** [comment]
If you are not seeing the icon, the parent folder is hidden and therefore all child elements, too. Can you unhide the parent folder, or is this also not working?
It may be related to the changes in Brave, since they seem to have added a show/hide mechanism as well.

**Comment by megaroeny** [comment]
Not seeing a root folder anymore. This was something Brave removed since it was redundant. Maybe that's why?

![No Hide Bookmark toggle](https://user-images.githubusercontent.com/1559447/72279662-9c673500-3604-11ea-8a77-55772875f7de.gif)

**Comment by Kiuryy** [comment]
I think this is the problem. I just installed Brave to test this, but it seems to work. This is very likely only happening when upgrading the bookmark data in the latest version of Brave. Can you uninstall the extension and reinstall it, to see if the problem is gone then?

**Comment by megaroeny** [comment]
That worked, thanks!
