### ISSUE TITLE
Cloud backup service

### ISSUE THREAD

**Issue by Vstory** [Kiuryy/Bookmark_Sidebar#89]
Can Bookmark Sidebar add cloud backup capabilities?
Support webdav protocol, etc. Cloud backups can be used to restore bookmark sidebar configurations on other devices.

**Comment by Kiuryy** [comment]
The settings are already saved in your Google account per default and will be automatically synced across your devices when you are logged in with your Google account. As backup you can also export your configuration in the settings of the extension, which gives you a file, you can put into your cloud directory or example.
Adding Third-Party-Cloud services is very complex (which to add? The extension is being used all over the world) and requires heavy maintainance to implement the APIs of them all. When taking into account, that this sync mechanism is already handled by Chrome, I don't think adding this is worth the effort.

**Comment by Vstory** [comment]
I understand.Thank you!
