### ISSUE TITLE
Difficult to operate with two screens

### ISSUE THREAD

**Issue by dijiagui** [Kiuryy/Bookmark_Sidebar#93]
I have two extended screen for my mac.It`s hard for me to wakeup tag because my mouse may move to another screen.Is there any way to solve it?Thanks.

**Comment by Kiuryy** [comment]
There is no way of detecting whether you are using two monitors or on which of them you have opened the browser window. But there are other ways I implemented to face this problem:

You can configure the extension to open only when clicking the extension icon or using a keyboard shortcut. This will disable the mouseover/click functionality.

Another way of reducing trouble when clicking things on the side of the browser window or moving to your second monitor is, to change where the sidebar can be opened vertically.
The options for this can be found in the settings of the extension under "Sidebar" > "Toggle" called "Configure area". For example, you can set the sidebar to only open in the lower left corner of the browser window. Maybe this is something for your :)

**Comment by dijiagui** [comment]
It`s help, I change the width to 50px in "Configure area",this becomes very useful,thanks.
