### ISSUE TITLE
If tabs are separated in different windows, some window will have double sidebar when opened

### ISSUE THREAD

**Issue by pingshunhuangalex** [Kiuryy/Bookmark_Sidebar#94]
I'm using Mac Catalina. To reproduce the issue:
1. Open a Chrome window and open multiple tabs.
2. Drag some tabs out of the current window to create multiple windows
3. In the newly created window, click the bookmark sidebar icon to open the sidebar
4. You'll see both the sidebar and the dark shades covering the screen area are duplicated in some of the window

It'd be nice if this bug can be fixed soon cuz it can be quite annoying. Other than that, great extension. Please keep up the good work.

**Comment by Kiuryy** [comment]
I just tested it myself with the mentioned steps but could not reproduce such a behaviour. I'm using Windows though, with the latest version of Chrome, so maybe the mechanism of spawning a new Chrome window is different here.
The issue you mention seems to indicate, that the sidebar is getting loaded multiple times for some tabs.
I will try to figure out what is causing this and how to fix it, but cannot guarantee this can be resolved.
