### ISSUE TITLE
Use empty new tabs when open up a bookmark in foreground

### ISSUE THREAD

**Issue by pingshunhuangalex** [Kiuryy/Bookmark_Sidebar#95]
A very nice experience I had with other bookmark extensions is some of them utilise the new tabs that haven't opened up any pages yet, i.e. when you open a page in the foreground, it'll first use the empty new tabs if there's any before creating new tabs. Opening page in background (vie mouse wheel) should remain the same.

This can be especially helpful for this extension because opening sidebar creates a dedicate new tab page for me (I got a specific new tab page I want to use so can't use sidebar's new tab page).

Hopefully, there will be an option to do that. Thanks.

**Comment by Kiuryy** [comment]
This would require an option in the settings of the extension, which then will use existing tabs with a "New tab page" first when you click on "Open in new tab" in the sidebar (or configured that a left click opens them in a new tab).

I think this is a very rare use case and therefore would rather fit in the expert settings of the extension. I need to first evaluate how much work and adaptions in the code is needed to implement this and whether this is worth the effort.

A technical problem here is, that the extension currently is not aware of your tabs URLs, so doesn't know whether you have a "New tab" page already opened. This requires an additional permission to be asked for.

**Comment by pingshunhuangalex** [comment]
Mmm, maybe other bookmark extensions require more permission by default. It's ok, it's just good to have to me. I don't mind we leave it as it is if it's difficult. Thanks.
